/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package biblioteca.telasDesign;


import biblioteca.telas.ListaLivros;
import biblioteca.telas.RegistarLivros;
import java.awt.Graphics;
import java.io.File;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;


/**
 *
 * @author Dioneria Matavele
 */
public class DesignMenuAdmin extends javax.swing.JPanel {

     BufferedImage imagemFundo;
    /**
     * Creates new form MenuAdmin
     */
    public DesignMenuAdmin() {
        initComponents();
        
        try {
            this.imagemFundo = ImageIO.read(new File("C:\\Users\\Dioneria Matavele\\Pictures\\telaas\\Login.png"));
            
        } catch (IOException ex) {
            Logger.getLogger(DesignLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
     protected void paintComponent(Graphics g){
        super.paintComponent(g);
        
        g.drawImage(imagemFundo.getScaledInstance(550, 500, 0), 0, 0, null);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Registarbtn = new javax.swing.JButton();
        Procurarbtn = new javax.swing.JButton();
        LivrosDis = new javax.swing.JButton();
        LivrosEmp = new javax.swing.JButton();
        lisClientes = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        Registarbtn.setBackground(new java.awt.Color(255, 145, 77));
        Registarbtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Registarbtn.setText("Registar Livros");
        Registarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistarbtnActionPerformed(evt);
            }
        });

        Procurarbtn.setBackground(new java.awt.Color(255, 145, 77));
        Procurarbtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Procurarbtn.setText("Procurar Livro");
        Procurarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProcurarbtnActionPerformed(evt);
            }
        });

        LivrosDis.setBackground(new java.awt.Color(255, 145, 77));
        LivrosDis.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        LivrosDis.setText("Livros Disponiveis");
        LivrosDis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LivrosDisActionPerformed(evt);
            }
        });

        LivrosEmp.setBackground(new java.awt.Color(255, 145, 77));
        LivrosEmp.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        LivrosEmp.setText("Livros Emprestados");
        LivrosEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LivrosEmpActionPerformed(evt);
            }
        });

        lisClientes.setBackground(new java.awt.Color(255, 145, 77));
        lisClientes.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lisClientes.setText("Lista de Clientes");
        lisClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lisClientesActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 145, 77));
        jButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lisClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LivrosDis, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Registarbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Procurarbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LivrosEmp)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(jButton1)))
                .addContainerGap(202, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(221, Short.MAX_VALUE)
                .addComponent(Registarbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LivrosDis)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Procurarbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LivrosEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lisClientes)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(69, 69, 69))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void RegistarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistarbtnActionPerformed
       new RegistarLivros().setVisible(true);
       
       
    }//GEN-LAST:event_RegistarbtnActionPerformed

    private void ProcurarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProcurarbtnActionPerformed
        new Pesquisar().setVisible(true);
        
       
    }//GEN-LAST:event_ProcurarbtnActionPerformed

    private void LivrosDisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LivrosDisActionPerformed
       new ListaLivros().setVisible(true);
       
    }//GEN-LAST:event_LivrosDisActionPerformed

    private void LivrosEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LivrosEmpActionPerformed
       new ListaLivros().setVisible(true);
       
    }//GEN-LAST:event_LivrosEmpActionPerformed

    private void lisClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lisClientesActionPerformed
        new ListaLivros().setVisible(true);
    }//GEN-LAST:event_lisClientesActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new DesignLogin().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LivrosDis;
    private javax.swing.JButton LivrosEmp;
    private javax.swing.JButton Procurarbtn;
    private javax.swing.JButton Registarbtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton lisClientes;
    // End of variables declaration//GEN-END:variables
}
