/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package biblioteca.telasDesign;

import Livro.Livros;
import BaseDeDados.BaseDeDadosLivro;
import javax.swing.JOptionPane;

/**
 *
 * @author Dell
 */
public class DesignTelaPesquisa extends javax.swing.JPanel {

    /**
     * Creates new form DesignTelaPesquisa
     */
    public DesignTelaPesquisa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filtroC = new javax.swing.JComboBox<>();
        pesquisarTxt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JLabel();
        txtGen = new javax.swing.JLabel();
        txtAutor = new javax.swing.JLabel();
        txtQuant = new javax.swing.JLabel();
        txtPreco = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        filtroC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Filtro", "Titulo", "Genero", "Autor" }));

        pesquisarTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarTxtActionPerformed(evt);
            }
        });

        jButton1.setText("Pesquisar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Titulo");

        jLabel2.setText("Genero");

        jLabel3.setText("Autor");

        jLabel4.setText("Quantidade ");

        jLabel5.setText("Preco");

        txtTitulo.setText("Tit");

        txtGen.setText("Gen");

        txtAutor.setText(" Aut");

        txtQuant.setText("quant");

        txtPreco.setText("Preco");

        jButton2.setText("Voltar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(pesquisarTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jButton1)
                            .addGap(17, 17, 17)
                            .addComponent(filtroC, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(106, 106, 106)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                                .addComponent(txtGen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtAutor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtQuant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtPreco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filtroC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pesquisarTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTitulo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtGen))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtAutor))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtQuant))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtPreco))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(108, 108, 108))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void pesquisarTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pesquisarTxtActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if (filtroC.getSelectedItem().equals("Titulo")) {

            String pesquisa = pesquisarTxt.getText();
            BaseDeDadosLivro li = new BaseDeDadosLivro();
            Livros livro = (li.PesquisarLivrosT(pesquisa));
            if (livro == null) {
                JOptionPane.showMessageDialog(null, "Autor nao Registado");
            } else {
                txtTitulo.setText(livro.getTitulo());
                txtGen.setText(livro.getGenero());
                txtAutor.setText(livro.getAutor());

            }
        } else if (filtroC.getSelectedItem().equals("Genero")) {

            String pesquisa = pesquisarTxt.getText();
            BaseDeDadosLivro li = new BaseDeDadosLivro();
            Livros livro = (li.PesquisarLivrosG(pesquisa));
            if (livro == null) {
                JOptionPane.showMessageDialog(null, "Genero Inexistente");
            } else {
                txtTitulo.setText(livro.getTitulo());
                txtGen.setText(livro.getGenero());
                txtAutor.setText(livro.getAutor());

            }
        } else if (filtroC.getSelectedItem().equals("Autor")) {

            String pesquisa = pesquisarTxt.getText();
            BaseDeDadosLivro li = new BaseDeDadosLivro();
            Livros livro = (li.PesquisarLivrosG(pesquisa));
            if (livro == null) {
                JOptionPane.showMessageDialog(null, "Nao existe livro disponivel com nome deste autor");
            } else {
                txtTitulo.setText(livro.getTitulo());
                txtGen.setText(livro.getGenero());
                txtAutor.setText(livro.getAutor());

            }

        } else if (filtroC.getSelectedItem().equals("Ano")) {

            String pesquisa = pesquisarTxt.getText();
            BaseDeDadosLivro li = new BaseDeDadosLivro();
            Livros livro = (li.PesquisarLivrosA(pesquisa));
            if (livro == null) {
                JOptionPane.showMessageDialog(null, "Nao exste Livro disponivel lancado neste ano");
            } else {
                txtTitulo.setText(livro.getTitulo());
                txtGen.setText(livro.getGenero());
                txtAutor.setText(livro.getAutor());
                txtQuant.setText(livro.getQuantEstoque());
            }
        }
     }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new DesignMenuAdmin().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> filtroC;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField pesquisarTxt;
    private javax.swing.JLabel txtAutor;
    private javax.swing.JLabel txtGen;
    private javax.swing.JLabel txtPreco;
    private javax.swing.JLabel txtQuant;
    private javax.swing.JLabel txtTitulo;
    // End of variables declaration//GEN-END:variables
}
